name: flutter_exercise_camera
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera_camera:
  image_picker:
  get:
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#F9D87B"
  image: "assets/app/splash.png"
  android: true
  ios: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
